# Navigation Links
# ALL LINKS MUST BE LOWER_CASE
#   To link a homepage section, specify the URL as a hash `#` followed by the filename of the
#     desired section in `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
# This is the default-language menu
# Specific values needing translation must be provided in languages.toml

[[main]]
name = "ANL-Home"
url = "/"          # Home page top
weight = 10

[[main]]
name = "What's On"
url = "/01_whats_on"
weight = 20

[[main]]
name = "About Us"
url = "/02_about_anl"
weight = 30

[[main]]
name = "Safeguarding"
url = "/03_safeguarding"
weight = 30

[[main]]
name = "Pray"
url = "/04_pray" 
weight = 40

[[main]]
name = "Give"
url = "/05_give" 
weight = 50

[[main]]
name = "Login"
url = "user-login"
weight = 100

[[main]]
name = "Secure"
url = "/06_secure"
weight = 110


  
