[build]
  command = "node build_scripts/generate_qr.js \
&& node build_scripts/buildSecureContent.js \
&& echo 'PWD:' && pwd \
&& echo 'LS PRIVATE_HTML:' \
&& ( ls -R private_html || echo 'private_html missing' ) \
&& echo '--- COPYING PRIVATE_HTML ---' \
&& mkdir -p netlify/functions/private_html \
&& cp -a private_html/. netlify/functions/private_html/ \
&& echo '--- COPY DONE ---' \
&& hugo --gc --minify -b $URL"
  publish = "public"
  
[build.environment]
  HUGO_VERSION = "0.78.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
    
[functions]
  included_files = ["netlify/functions/private_html/**/*"]
